#!/usr/bin/env python3
"""Stage 1: use full videos to select InternData-A1 episodes with action errors."""

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import requests
from tqdm import tqdm

try:
    import termios
except ImportError:
    termios = None

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

SERVER_PORT = 8000
DEFAULT_TP_SIZE = 1
VIDEO_FPS = 8
MEM_FRACTION_STATIC = 0.85
DEFAULT_CONTEXT_LENGTH = 32768
DEFAULT_MAX_WORKERS = 8
PROMPT = (
    'You see synchronized frames sampled uniformly across the full episode from every camera view in a simulation environment.\n'
    'Task: "{task}"\n'
    'The frames are shown in chronological order and together cover the whole episode.\n'
    'First write a brief caption of what the robot does over the whole episode, using all views jointly.\n'
    'Then decide whether there is a clear action error in the motion itself.\n'
    'This is simulation data. The trajectories are generated by fixed rule-based policies under human-defined environment setups.\n'
    'Do NOT judge task completion, object choice, semantic goal correctness, or whether the task is unfinished.\n'
    'Assume the intended object and target are correct in the simulator setup. There is no "picked the wrong object", "placed at the wrong goal", or "did not finish" category here.\n'
    'Only mark action_error=true when the motion itself is clearly bad, such as an obvious failed grasp, dropping due to bad manipulation, severe unstable motion, collision-caused mishandling, or other clear execution mistakes visible in the video.\n'
    'Do not mark action_error=true for normal successful motion, slightly awkward trajectories, minor pauses, brief occlusion, rendering ambiguity, or harmless simulator artifacts.\n'
    'Return STRICT JSON only:\n'
    '{{"caption": "<3-4 sentences>", "reason": "<1-3 sentences>", "action_error": <true or false>}}'
    'Example 1:\n'
    'Task: "Pick up the cup and place it into the tray"\n'
    'Output: {{"caption": "The robot reaches for the cup, grasps it, moves it toward the tray, and places it smoothly.", "reason": "The whole motion is stable and consistent, with no obvious failed grasp, drop, or recovery caused by execution mistakes. In this simulation setting, do not penalize semantics beyond visible motion quality.", "action_error": false}}\n'
    'Example 2:\n'
    'Task: "Put the pen into the pen holder"\n'
    'Output: {{"caption": "The robot picks up the pen, moves it toward the pen holder, but the pen is not inserted and drops onto the table.", "reason": "The video shows a clear action execution failure: the robot does not successfully place the pen during the insertion motion, and the pen is dropped onto the table because of the bad manipulation. This is an action error in the simulated rule-based trajectory.", "action_error": true}}\n'
)


def save_terminal_state():
    if termios is None or not sys.stdin.isatty():
        return None
    try:
        return termios.tcgetattr(sys.stdin.fileno())
    except termios.error:
        return None


def restore_terminal_state(state):
    if termios is None or not sys.stdin.isatty():
        return
    fd = sys.stdin.fileno()
    try:
        if state is not None:
            termios.tcsetattr(fd, termios.TCSADRAIN, state)
            return
        attrs = termios.tcgetattr(fd)
        attrs[3] |= termios.ECHO | termios.ICANON
        termios.tcsetattr(fd, termios.TCSADRAIN, attrs)
    except termios.error:
        pass


def read_jsonl(path: Path):
    text = path.read_text().strip() if path.exists() else ""
    return [json.loads(line) for line in text.splitlines()] if text else []


def load_episode_tasks(subset_dir: Path):
    tasks = {}
    for row in read_jsonl(subset_dir / "meta" / "episodes.jsonl"):
        task = (row.get("tasks") or [""])[0].strip() or row.get("remarks", "").strip()
        if row.get("episode_index") is not None and task:
            tasks[int(row["episode_index"])] = task
    if tasks:
        return tasks
    for row in read_jsonl(subset_dir / "meta" / "tasks.jsonl"):
        if row.get("task", "").strip():
            return {"__fallback__": row["task"].strip()}
    name = subset_dir.name.split(".", 1)[-1] if "." in subset_dir.name else subset_dir.name
    return {"__fallback__": re.sub(r"([a-z])([A-Z])", r"\1 \2", name).lower()}


def collect_episodes(root: Path, subset: str | None):
    if subset:
        subset_path = root / subset
        subset_dirs = [subset_path] if (subset_path / "meta" / "info.json").exists() else sorted({p.parent.parent for p in subset_path.rglob("meta/info.json")})
    else:
        subset_dirs = sorted({p.parent.parent for p in root.rglob("meta/info.json")})
    episodes = []
    for subset_dir in subset_dirs:
        info = json.loads((subset_dir / "meta" / "info.json").read_text())
        fps = float(info.get("fps", 30))
        tasks = load_episode_tasks(subset_dir)
        lengths = {
            int(row["episode_index"]): int(row["length"])
            for row in read_jsonl(subset_dir / "meta" / "episodes.jsonl")
            if row.get("episode_index") is not None and row.get("length") is not None
        }
        fallback = tasks.get("__fallback__", "unknown task")
        subset_name = str(subset_dir.relative_to(root))
        episode_map = {}
        for video_path in sorted((subset_dir / "videos").glob("chunk-*/*/episode_*.mp4")):
            ep_idx = int(video_path.stem.split("_")[-1])
            entry = episode_map.setdefault(ep_idx, {
                "subset": subset_name,
                "episode_index": ep_idx,
                "task": tasks.get(ep_idx, fallback),
                "fps": fps,
                "num_frames": lengths.get(ep_idx),
                "views": {},
            })
            entry["views"][video_path.parent.name] = str(video_path.relative_to(root))
        for ep_idx in sorted(episode_map):
            entry = episode_map[ep_idx]
            frames = entry["num_frames"] or 0
            entry["duration_sec"] = frames / fps if frames > 0 else 0.0
            episodes.append(entry)
    return episodes


def call_vlm_json(client, model: str, content, max_retries: int):
    last_error = None
    for attempt in range(max_retries):
        try:
            resp = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": content}],
                max_tokens=4096,
                temperature=0.0 if attempt == 0 else 0.4,
                extra_body={"chat_template_kwargs": {"enable_thinking": False}},
            )
        except Exception as exc:
            last_error = exc
            if attempt + 1 < max_retries:
                time.sleep(min(2 * (attempt + 1), 10))
                continue
            raise
        raw_response = (resp.choices[0].message.content or "").strip()
        match = re.search(r"\{.*\}", raw_response, flags=re.S)
        if not match:
            continue
        try:
            return {
                "raw_response": raw_response,
                "parsed_json": json.loads(match.group(0)),
            }
        except json.JSONDecodeError:
            pass
    if last_error is not None:
        raise last_error
    return {"raw_response": raw_response if "raw_response" in locals() else "", "parsed_json": {}}


def launch_sglang_server(
    model_path: str,
    server_python: str | None,
    context_length: int,
    tp_size: int,
    reasoning_parser: str | None,
):
    python_bin = server_python or sys.executable
    cmd = [
        python_bin, "-m", "sglang.launch_server",
        "--model-path", model_path,
        "--port", str(SERVER_PORT),
        "--tp-size", str(tp_size),
        "--mm-process-config", json.dumps({"video": {"fps": VIDEO_FPS}}),
        "--mem-fraction-static", str(MEM_FRACTION_STATIC),
        "--context-length", str(context_length),
    ]
    if reasoning_parser:
        cmd += ["--reasoning-parser", reasoning_parser]
    proc = subprocess.Popen(cmd, stdout=sys.stdout, stderr=sys.stderr)
    for _ in range(1800):
        time.sleep(2)
        if proc.poll() is not None:
            raise RuntimeError(f"SGLang exited early. Check environment: {python_bin}")
        try:
            if requests.get(f"http://localhost:{SERVER_PORT}/health", timeout=3).status_code == 200:
                return proc
        except requests.ConnectionError:
            pass
    proc.kill()
    raise RuntimeError("SGLang server failed to start within 3600s")


def warn_if_model_may_not_be_multimodal(model_path: str):
    model_name = Path(model_path).name.lower()
    if "vl" in model_name or "vision" in model_name:
        return
    print(
        "[warning] model-path does not look like a vision-language model. "
        "If you pass a text-only model such as Qwen3.5-27B, image inputs may be ignored or fail.",
        file=sys.stderr,
        flush=True,
    )


def compact_episode_for_log(episode):
    first_view_name, first_view_path = next(iter(sorted(episode["views"].items())))
    return {
        **episode,
        "views": {first_view_name: first_view_path},
    }


def probe_video_duration(video_path: Path):
    ffprobe_bin = shutil.which("ffprobe")
    if not ffprobe_bin:
        raise RuntimeError("ffprobe is required")
    probe = subprocess.run(
        [
            ffprobe_bin,
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "json",
            str(video_path),
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    meta = json.loads(probe.stdout or "{}")
    return float((meta.get("format") or {}).get("duration", 0.0) or 0.0)


def extract_frame_at_sec(video_path: Path, output_path: Path, timestamp_sec: float):
    ffmpeg_bin = shutil.which("ffmpeg")
    if not ffmpeg_bin:
        raise RuntimeError("ffmpeg is required")
    subprocess.run(
        [
            ffmpeg_bin,
            "-v",
            "error",
            "-y",
            "-ss",
            f"{max(timestamp_sec, 0.0):.6f}",
            "-i",
            str(video_path),
            "-frames:v",
            "1",
            str(output_path),
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return output_path.resolve().as_uri()


def build_sample_timestamps(duration_sec: float, sample_count: int):
    if sample_count <= 1 or duration_sec <= 0:
        return [0.0]
    end_sec = max(duration_sec - 1e-3, 0.0)
    if end_sec <= 0:
        return [0.0] * sample_count
    return [end_sec * idx / (sample_count - 1) for idx in range(sample_count)]


def build_episode_content(data_root: Path, episode, prompt_text: str, frames_per_view: int, tmp_dir_path: Path):
    content = []
    for view_idx, (view_name, video_path) in enumerate(sorted(episode["views"].items())):
        resolved_path = data_root / video_path
        timestamps = build_sample_timestamps(probe_video_duration(resolved_path), frames_per_view)
        content.append({"type": "text", "text": f"View: {view_name}"})
        for frame_idx, timestamp_sec in enumerate(timestamps, start=1):
            frame_path = tmp_dir_path / f"view_{view_idx:02d}_frame_{frame_idx:02d}.png"
            frame_uri = extract_frame_at_sec(resolved_path, frame_path, timestamp_sec)
            content += [
                {
                    "type": "text",
                    "text": f"Frame {frame_idx}/{len(timestamps)} at {timestamp_sec:.2f}s from view {view_name}",
                },
                {"type": "image_url", "image_url": {"url": frame_uri}},
            ]
    content.append({"type": "text", "text": prompt_text})
    return content


def judge_action_error(client, model: str, data_root: Path, episode, max_retries: int, frames_per_view: int):
    prompt_text = PROMPT.format(task=episode["task"])
    with tempfile.TemporaryDirectory(prefix="clean_video_frames_") as tmp_dir:
        content = build_episode_content(data_root, episode, prompt_text, frames_per_view, Path(tmp_dir))
        review = call_vlm_json(client, model, content, max_retries)
    result = review["parsed_json"]
    compact_episode = compact_episode_for_log(episode)
    return {
        **compact_episode,
        "action_check": {
            "caption": str(result.get("caption", "")).strip(),
            "reason": str(result.get("reason", "")).strip(),
            "action_error": bool(result.get("action_error", False)),
        },
    }


def run_selection(args, client):
    data_root = Path(args.data_root)
    episodes = collect_episodes(data_root, args.subset)
    if args.limit:
        episodes = episodes[:args.limit]
    flagged = 0
    with open(args.output_json, "w", buffering=1) as fout:
        with ThreadPoolExecutor(max_workers=args.max_workers) as pool, tqdm(total=len(episodes), desc="Action-error filter", unit="episode") as pbar:
            futures = {
                pool.submit(
                    judge_action_error,
                    client,
                    args.model_path,
                    data_root,
                    episode,
                    args.max_retries,
                    args.frames_per_view,
                ): episode
                for episode in episodes
            }
            for fut in as_completed(futures):
                episode = futures[fut]
                try:
                    result = fut.result()
                except Exception as exc:
                    compact_episode = compact_episode_for_log(episode)
                    result = {
                        **compact_episode,
                        "action_check": {
                            "caption": "",
                            "reason": "",
                            "action_error": False,
                            "error": str(exc).strip(),
                        },
                    }
                fout.write(json.dumps(result) + "\n")
                if result["action_check"]["action_error"]:
                    flagged += 1
                pbar.set_postfix(flagged=flagged)
                pbar.update(1)
    print(f"Total episodes: {len(episodes)}")
    print(f"All episodes written to {args.output_json}: {len(episodes)}")
    print(f"Flagged episodes: {flagged}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-root", required=True)
    parser.add_argument("--output-json", required=True)
    parser.add_argument("--model-path", default="/project/vonneumann1/wcy/models/LLM/Qwen3.5-397B-A17B-FP8")
    parser.add_argument("--subset")
    parser.add_argument("--server-python")
    parser.add_argument("--tp-size", type=int, default=DEFAULT_TP_SIZE)
    parser.add_argument("--reasoning-parser")
    parser.add_argument("--context-length", type=int, default=DEFAULT_CONTEXT_LENGTH)
    parser.add_argument("--max-workers", type=int, default=DEFAULT_MAX_WORKERS)
    parser.add_argument("--max-retries", type=int, default=5)
    parser.add_argument("--frames-per-view", type=int, default=8)
    parser.add_argument("--limit", type=int)
    args = parser.parse_args()
    if OpenAI is None:
        raise ImportError("openai package is required")
    warn_if_model_may_not_be_multimodal(args.model_path)
    terminal_state = save_terminal_state()
    server_proc = launch_sglang_server(
        args.model_path,
        args.server_python,
        args.context_length,
        args.tp_size,
        args.reasoning_parser,
    )
    try:
        client = OpenAI(api_key="EMPTY", base_url=f"http://localhost:{SERVER_PORT}/v1", timeout=300)
        run_selection(args, client)
    finally:
        server_proc.kill()
        server_proc.wait()
        restore_terminal_state(terminal_state)
        print("Server stopped.")


if __name__ == "__main__":
    main()

'''
python clean_video.py \
  --data-root /project/vonneumann1/wcy/code/starVLA-dev/playground/Datasets/InternData-A1 \
  --output-json /project/vonneumann1/wcy/code/starVLA-dev/playground/Datasets/InternData-A1/clean_results/final_frame_errors_test.jsonl \
  --subset sim_updated/pick_and_place_tasks/split_aloha/parallel_pick_and_place_right_right/parallel_pick_and_place_right_right/bowl \
  --model-path /project/vonneumann1/wcy/models/LLM/Qwen3.5-27B \
  --limit 20

stty echo sane

'''